backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use backend\models\UploadFile;
use yii\web\UploadedFile;
use backend\models\SendEmailForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@', '?'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

	public function actionUploadFile()
	{
		$model = new UploadFile();

		if (Yii::$app->request->isPost) {
			$model->file = UploadedFile::getInstance($model, 'file');
			if ($model->uploadFile()) {
				Yii::$app->session->setFlash('success', "Новый файл загружен.");
			}
			else {
				Yii::$app->session->setFlash('error', "Не удалось загрузить новый файл.");
			}
		}

		return $this->render('upload-file', ['model' => $model]);
	}

	public function actionSendEmail()
	{
		$model = new SendEmailForm();

		if (Yii::$app->request->isPost) {
			$model->recipients = Yii::$app->request->post('SendEmailForm')['recipients'];
			$model->template = Yii::$app->request->post('SendEmailForm')['template'];
			$flag = true;

			foreach ($model->recipients as $user_email) {
				if (!$this->sendEmail($model->template, SendEmailForm::$email_subjects[$model->template], $user_email)) {
					$flag = false;
				}
			}

			if ($flag) {
				Yii::$app->session->setFlash('success', 'Письма отправлены.');
				return $this->goHome();
			}
			else {
				Yii::$app->session->setFlash('error', 'Ошибка отправки писем.');
			}

			return $this->refresh();

		}
		else {
			return $this->render('send-email', compact('model'));
		}
	}

	public function actionDownloadAdminGuideFile()
	{
		return Yii::$app->response->sendFile(Yii::getAlias('@backend') .'/web/uploads/admin_guide_scrathouse.doc');
	}

	protected function sendEmail($template, $subject, $to)
	{
		return Yii::$app->mailer
			->compose($template)
			->setTo($to)
			->setFrom(Yii::$app->params['adminEmail'])
			->setSubject($subject)
			->send();
	}
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use common\models\ContactForm;
use backend\models\Shops;
use common\models\ContactPhoneForm;
use common\services\auth\SignupService;
use common\models\User;
use frontend\models\Auth;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\db\Exception;

/* @var $auth Auth */
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
	            'class' => 'yii\authclient\AuthAction',
	            'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
	    if (!Yii::$app->user->isGuest) {
		    return $this->goHome();
	    }

	    $form = new LoginForm();

	    if (Yii::$app->request->isAjax && $form->load(Yii::$app->request->post())) {
		    Yii::$app->response->format = Response::FORMAT_JSON;
		    return ActiveForm::validate($form);
	    }

	    if ($form->load(Yii::$app->request->post())) {
		    try {
			    if ($form->login()) {
				    return $this->goHome();
			    }
			    else {
				    Yii::$app->session->setFlash('error', 'Не верно введены логин или пароль!');
				    return $this->goHome();
			    }
		    }
		    catch (\DomainException $e) {
			    Yii::$app->session->setFlash('error', $e->getMessage());
			    return $this->goHome();
		    }
	    }
	    return $this->goHome();
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


	public function onAuthSuccess($client)
	{
		$attributes = $client->getUserAttributes();
		//echo $attributes['name']['familyName'];
//		echo '<pre>';
//		var_dump($attributes);
//		die;
		$auth = Auth::find()->where([
			'source' => $client->getId(),
			'source_id' => $attributes['id'],
		])->one();

		if (empty($attributes['email']) && empty($attributes['emails'])) {
			Yii::$app->getSession()->setFlash('error', 'Ошибка авторизации! Пустой email.');
			return false;
		}
		if (Yii::$app->user->isGuest) {
			if ($auth) { // авторизация
				$user = $auth->user;
				if ($this->updateUserInfo($user)) {
					Yii::$app->user->login($user, Yii::$app->params['user.rememberMeDuration']);
					Yii::$app->getSession()->setFlash('success', 'Вы удачно авторизировались!');
				}
				else {
					Yii::$app->getSession()->setFlash('error', 'Ошибка авторизации!');
				}
			}
			else { // регистрация
				switch ($client->name) {
					case 'google':
						$existingUser = User::findOne(['email' => $attributes['emails'][0]['value']]);
						break;
					default:
						$existingUser = User::findOne(['email' => $attributes['email']]);
						break;
				}
				if ($existingUser) {
					$auth = new Auth( [
						'user_id'   => $existingUser->id,
						'source'    => $client->getId(),
						'source_id' => (string) $attributes['id'],
					] );
					if ( $this->updateUserInfo( $existingUser ) && $auth->save() ) {
						Yii::$app->user->login( $existingUser, Yii::$app->params['user.rememberMeDuration'] );
						Yii::$app->getSession()->setFlash('success', 'Вы удачно авторизировались!');
					}
					else {
						Yii::$app->getSession()->setFlash( 'error', $auth->getErrors(), [ 'client' => $client->getTitle() ] );
					}
				}
				else {
					$password = Yii::$app->security->generateRandomString( 16 );
					switch ($client->name) {
						case 'google':
							$user = new User( [
								'last_name' => $attributes['name']['familyName'],
								'first_name'  => $attributes['name']['givenName'],
								'email'      => $attributes['emails'][0]['value'],
								'password'   => $password,
								'status'     => User::STATUS_ACTIVE,
							] );
							break;
						default:
							$name = explode( ' ', $attributes['name'] );
							$user = new User( [
								'first_name' => $name[0],
								'last_name'  => $name[1],
								'email'      => $attributes['email'],
								'password'   => $password,
								'status'     => User::STATUS_ACTIVE,
							] );
							break;
					}

					$user->generateAuthKey();
					$user->generatePasswordResetToken();
					$transaction = $user->getDb()->beginTransaction();
					if ( $user->save() ) {
						$auth = new Auth( [
							'user_id'   => $user->id,
							'source'    => $client->getId(),
							'source_id' => (string) $attributes['id'],
						] );
						if ( $auth->save() ) {
							$transaction->commit();
							Yii::$app->user->login( $user, Yii::$app->params['user.rememberMeDuration'] );
							Yii::$app->getSession()->setFlash('success', 'Вы удачно авторизировались!');
						}
						else {
							$transaction->rollBack();
							Yii::$app->getSession()->setFlash( 'error', $auth->getErrors(), [ 'client' => $client->getTitle() ] );
						}
					}
					else {
						$transaction->rollBack();
						Yii::$app->getSession()->setFlash( 'error', 'Ошибка авторизации', [ 'client' => $client->getTitle() ] );
					}
				}
			}
		}
		else { // Пользователь уже зарегистрирован
			if (!$auth) { // добавляем внешний сервис аутентификации
				$auth = new Auth([
					'user_id' => Yii::$app->user->id,
					'source' => $client->getId(),
					'source_id' => $attributes['id'],
				]);
				$auth->save();
			}
		}
		return true;
	}

	public function updateUserInfo($user)
	{
		if ($user->status === User::STATUS_WAIT) {
			$password = Yii::$app->security->generateRandomString(16);
			$user->status = User::STATUS_ACTIVE;
			$user->password = $password;
			return $user->save();
		}
		return $user->status !== User::STATUS_BLOCKED;
	}

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
	    $form = new SignupForm();

	    if (Yii::$app->request->isAjax && $form->load(Yii::$app->request->post())) {
		    Yii::$app->response->format = Response::FORMAT_JSON;
		    return ActiveForm::validate($form);
	    }

	    if ($form->load(Yii::$app->request->post()) && $form->validate()) {
		    $signupService = new SignupService();

		    try{
			    $user = $signupService->signup($form);
			    Yii::$app->session->setFlash('success', 'Для окончания регистрации подтвердите Ваш email.');
			    $signupService->sentEmailConfirm($user);
			    return $this->goHome();
		    }
		    catch (\RuntimeException $e){
			    Yii::$app->errorHandler->logException($e);
			    Yii::$app->session->setFlash('error', $e->getMessage());
		    }
	    }
	    else {
		    Yii::$app->session->setFlash('error', 'Oops... Произошла ошибка при регистрации. Пожалуйста, проверьте вводимые Вами данные.');
	    }
	    return $this->goHome();
    }


	public function actionSignupConfirm($token)
	{
		$signupService = new SignupService();

		try{
			$signupService->confirmation($token);
			Yii::$app->session->setFlash('success', 'Вы успешно зарегистрировались.');
		}
		catch (\Exception $e){
			Yii::$app->errorHandler->logException($e);
			Yii::$app->session->setFlash('error', $e->getMessage());
		}

		return $this->goHome();
	}

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Проверьте Ваш email для дальнейших инструкций.');

                return $this->goHome();
            }
            else {
                Yii::$app->session->setFlash('error', 'Извините, мы не можем изменить пароль для введённого email.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        }
        catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Новый пароль сохранён.');

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use backend\assets\AppAsset;

$this->title = $name;
AppAsset::register($this);
\frontend\assets\ProductsAsset::register($this);
?>

<div class="site-error container">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
		<?= nl2br(Html::encode($message)) ?>
    </div>

    <br>

    <p>
        В результате обработки Вашего запроса случилась ошибка.
    </p>

    <br>

    <p>
        Пожалуйста, <a href="<?= \yii\helpers\Url::to(['/site/contact'])?>">сообщите нам,</a> если Вы думаете, что это ошибка сервера. Спасибо.
    </p>

    <br>

</div>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */
use backend\assets\AppAsset;

AppAsset::register($this);

$this->title = 'Scrathouse';
?>
<div class="site-index container">

    <div class="jumbotron">
        <h2>Scrathouse</h2>

        <p class="lead">Панель администратора.</p>

	    <?php if (\common\models\User::isSuperAdmin(Yii::$app->user->id)): ?>
            <h5><a href="/site/upload-file">Загрузка файла руководства администратора</a></h5>
        <?php endif; ?>

        <div class="row">
            <ul>
                <li><a href="/backend/web/order">Заказы</a></li>
                <li><a href="/backend/web/user">Пользователи</a></li>
                <li><a href="/backend/web/products">Товары</a></li>
                <li><a href="/backend/web/category">Категории</a></li>
                <li><a href="/backend/web/shops">Магазины</a></li>
                <li><a href="/backend/web/payments-type">Способы оплаты</a></li>
                <li><a href="/backend/web/text-by-admin">Настраиваемый текст</a></li>
                <li><a href="/backend/web/contact-info">Контакты</a></li>
                <li><a href="/backend/web/promo">Промокоды</a></li>
                <li><a href="/backend/web/points-categories">Бонусные категории</a></li>
                <li><a href="/backend/web/points">Бонусные баллы</a></li>
                <li><a href="/backend/web/points-histories">История бонусов</a></li>
                <li><a href="/backend/web/admin-numbers">Цифры</a></li>
                <li><a href="/backend/web/articles">Статьи</a></li>
                <li><a href="/backend/web/contact-form">Обратная связь</a></li>
                <li><a href="/backend/web/contact-phone-form">Обратный звонок</a></li>
                <li><a href="/backend/web/site/send-email">Рассылка писем</a></li>
            </ul>
        </div>
    </div>
</div>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

use backend\assets\AppAsset;

$this->title = 'Scrathouse';

AppAsset::register($this);

?>
<div class="site-login container">
    <p>Введите email и пароль администратора:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div class="form-group">
                    <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/site/send-email.php
<?php

/* @var $this yii\web\View */

use backend\models\SendEmailForm;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use backend\assets\AppAsset;
use dosamigos\multiselect\MultiSelect;

$this->title = 'Рассылка писем';
$this->params['breadcrumbs'][] = $this->title;

AppAsset::register($this);

?>

<div class="send-email-form">

	<?php $form = ActiveForm::begin(); ?>

	<?= $form->field($model, 'recipients')->widget(MultiSelect::className(),[
		"options" => ['multiple'=>"multiple"],
		"data" => \yii\helpers\ArrayHelper::map(SendEmailForm::findUsers(),'email', 'name'),
		"clientOptions" =>
			[
				"includeSelectAllOption" => true,
				'numberDisplayed' => 5
			],
	]) ?>

	<?= $form->field($model, 'template')->dropDownList(SendEmailForm::$templates_list) ?>

    <div class="form-group">
		<?= Html::submitButton('Отправить', ['class' => 'btn btn-success']) ?>
    </div>

	<?php ActiveForm::end(); ?>

</div>

backend/views/site/upload-file.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use backend\assets\AppAsset;

AppAsset::register($this);

$this->title = 'Загрузка руководства администратора';

/* @var $this yii\web\View */
/* @var $model backend\models\TextByAdmin */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="text-by-admin-form">

    <button style="margin-bottom: 50px;">
		<?= Html::a(Yii::t('app', 'Скачать руководство администратора'), ['site/download-admin-guide-file'],
			['style' => 'text-decoration: none; padding: 30px; color: #000;']) ?>
    </button>

	<?php if (\common\models\User::isSuperAdmin(Yii::$app->user->id)): ?>

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'file')->fileInput() ?>

        <div class="form-group">
            <?= Html::submitButton('Загрузить руководство', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    <?php endif; ?>
</div>